#!/bin/bash
DEST=$1
DURATION=$2
INPUT=2

if [ -z "${DEST}" ] ; then
    echo Need a filename
    exit 1
fi
if [ -z "${DURATION}" ] ; then
    echo How long to record for
    exit 1
fi

BASE="${DEST%.*}"
# Only save as mp4
DEST="${BASE}.mp4"

vlc v4l2:// :v4l2-dev=/dev/video0 :v4l2-width=720 :v4l2-height=480 :v4l2-input=2 :standard=0 :input-slave=alsa://hw:0,0 --sout="#duplicate{dst=display,dst={transcode{venc=x264{profile=baseline},vcodec=h264,vb=2000,acodec=mpga,ab=128}:std{access=file,mux=mp4,dst='${DEST}'}}}" --run-time=${DURATION} vlc://quit

# This will dump exact copy of stream from card. 60-70 gigs per hour!
#vlc v4l2:// :v4l2-dev=/dev/video0 :v4l2-width=720 :v4l2-height=480 :v4l2-input=2 :standard=0 :input-slave=alsa://hw:0,0 --sout="#duplicate{dst=std{access=file,dst='${DEST}'}, dst=display}" --run-time=${DURATION} vlc://quit

#v4lctl setinput ${INPUT}
#ffmpeg -f alsa -ac 2 -i hw:0,0 -f video4linux2 -i /dev/video0 -s 720x480 -aspect 4:3 -vcodec libx264 -preset ultrafast -acodec libfaac -t ${DURATION} ${DEST}

