#!/usr/bin/env python
#
# Copyright 2016 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

import subprocess
import os
import datetime
import argparse
import re

parser = argparse.ArgumentParser()
parser.add_argument("files", nargs="+", help="Video to join")
args = parser.parse_args()

lengths = [0]
for video in args.files:
  curpos = lengths[-1]
  cmd = "ffmpeg -i \"%s\" -f ffmetadata 2>&1 | grep 'Chapter #'" % video
  last = 0
  with os.popen(cmd) as f:
    for line in f:
      fields = line.split()
      begin = float(re.sub(",", "", fields[3]))
      len = begin - last
      lengths.append(curpos + begin)
      last = begin

  cmd = "vidinf \"%s\" | grep ID_LENGTH | sed -e 's/ID_LENGTH=//'" % video
  process = os.popen(cmd)
  len = float(process.read())
  process.close()
  lengths.append(curpos + len)
      
#lengths.pop()
lengths.pop(0)

print "CHAPTER01=00:00:00.00"
print "CHAPTER01NAME=Opening"
segnum = 1
pos = 0
for segpos in lengths:
#  pos += 0.25
#  pos += segpos
  pos = segpos
  offset = str(datetime.timedelta(seconds = pos))
  offset = offset[:-4]
  print "CHAPTER%02i=0%s" % (segnum + 1, offset)
  print "CHAPTER%02iNAME=Chapter %i" % (segnum + 1, segnum)
  segnum += 1

