#!/bin/sh
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

TY="$1"
MPG="${TY%.*}.mpg"
MKV="${TY%.*}.mkv"

tytompg -i "${TY}" -o "${MPG}"
ffmpeg -i "${MPG}" -vcodec libx264 -preset veryfast -x264opts crf=23:videoformat=undef:force-cfr -acodec ac3 -ab 448k -deinterlace "${MKV}"
rm -f "${MPG}"
