#!/bin/sh
FFMPEG=~/stuff/FFmpeg/ffmpeg
FFMPEG_LIBS=~/stuff/FFmpeg/lib*
FFMPEG_ARGS="-ac 2 -pix_fmt yuv411p -r 30000/1001"
export LD_LIBRARY_PATH=$(echo $FFMPEG_LIBS | sed -e 's/ /:/g')

INPUT="$1"
OUTPUT="$2"

if [ -z "${OUTPUT}" ] ; then
    OUTPUT="${INPUT%.*}.dv"
fi

echo ${OUTPUT}

width=720
height=480
#${FFMPEG} -i "${INPUT}" -filter:v "scale=iw*min($width/iw\,$height/ih):ih*min($width/iw\,$height/ih), pad=$width:$height:($width-iw*min($width/iw\,$height/ih))/2:($height-ih*min($width/iw\,$height/ih))/2" ${FFMPEG_ARGS} "${OUTPUT}"
#${FFMPEG} -i "${INPUT}" -filter:v "crop=ih/3*4:ih,scale=$width:$height" ${FFMPEG_ARGS} "${OUTPUT}"
${FFMPEG} -i "${INPUT}" -filter:v "scale=$width:$height" ${FFMPEG_ARGS} "${OUTPUT}"
