#!/bin/sh
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

DESTINATION=ayce:/buffet/public/video/Home-Movies/.

while [ $# -gt 0 -a `expr substr "${1:-empty}" 1 2` = "--" ] ; do
    case "$1" in
	--dest|--destination) 
	    DESTINATION="$2"
	    shift 2
	    ;;
	--duration)
	    FLAGS="${FLAGS} -duration $2"
	    shift 2
	    ;;
	--decomb)
	    FLAGS="${FLAGS} --decomb"
	    shift
	    ;;
	*)
	    echo unknown flag "$1"
	    exit 1
	    ;;
    esac
done

TAPE=$1

if [ -z "${TAPE}" ] ; then
   echo Please specify tape name
   exit 1
fi
  
TDIR=~/Videos/"${TAPE}"

if [ -z "${FLAGS}" ] ; then
    FLAGS=-d
fi

mkdir -p "${TDIR}"
cd "${TDIR}"
if [ ! -e "${TAPE}.mp4" ] ; then
   if [ ! -s all.dv ] ; then
       date
       dvgrab -rewind
       date
       dvcont rewind
       pv dv* > all.dv
   fi
   
   HandBrakeCLI ${FLAGS} -i all.dv -o "${TAPE}.mp4"
fi

rsync -P "${TAPE}.mp4" "${DESTINATION}"
