#!/bin/sh
PATH=/home/fozztexx/Unix/linux/bin:$PATH
AUTODIR=/buffet/public/video/BR/auto
MINAGE=1h

# FIXME - check lock age
if autorip --minage=${MINAGE} --check ${AUTODIR} ; then
    cd ${AUTODIR}/..
    viddin autorip --minage=${MINAGE} ${AUTODIR}
fi
