#!/bin/sh
DVD=/dev/dvd
if [ -n "$1" ] ; then
    DVD="$1"
fi

if [ ! -e "$DVD" ] ; then
    echo "$DVD" not found
    exit 1
fi

if [ ! -f "${DVD}" -a ! -d "${DVD}" ] ; then
    echo Waiting for online
    while true ; do
	BLKID=$(blkid "$DVD")
	if [ -n "$BLKID" ] ; then
	    break
	fi
    done
fi

lsdvd "$DVD" | grep Title | grep -v 0:00: | sed -e 's/ 00:/    /g'
