# Copyright 2020 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

dvdLanguage = {
  'Abkhazian': 'abk',
  'Afar': 'aar',
  'Afrikaans': 'afr',
  'Akan': 'aka',
  'Albanian': 'alb',
  'Amharic': 'amh',
  'Arabic': 'ara',
  'Aragonese': 'arg',
  'Armenian': 'arm',
  'Assamese': 'asm',
  'Avaric': 'ava',
  'Avestan': 'ave',
  'Aymara': 'aym',
  'Azerbaijani': 'aze',
  'Bambara': 'bam',
  'Bashkir': 'bak',
  'Basque': 'baq',
  'Belarusian': 'bel',
  'Bengali': 'ben',
  'Bihari languages': 'bih',
  'Bislama': 'bis',
  'Bokmål, Norwegian; Norwegian Bokmål': 'nob',
  'Bosnian': 'bos',
  'Breton': 'bre',
  'Bulgarian': 'bul',
  'Burmese': 'bur',
  'Catalan; Valencian': 'cat',
  'Central Khmer': 'khm',
  'Chamorro': 'cha',
  'Chechen': 'che',
  'Chichewa; Chewa; Nyanja': 'nya',
  'Chinese': 'chi',
  'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic': 'chu',
  'Chuvash': 'chv',
  'Cornish': 'cor',
  'Corsican': 'cos',
  'Cree': 'cre',
  'Croatian': 'hrv',
  'Czech': 'cze',
  'Danish': 'dan',
  'Divehi; Dhivehi; Maldivian': 'div',
  'Dutch; Flemish': 'dut',
  'Dzongkha': 'dzo',
  'English': 'eng',
  'Esperanto': 'epo',
  'Estonian': 'est',
  'Ewe': 'ewe',
  'Faroese': 'fao',
  'Fijian': 'fij',
  'Finnish': 'fin',
  'French': 'fre',
  'Fulah': 'ful',
  'Gaelic; Scottish Gaelic': 'gla',
  'Galician': 'glg',
  'Ganda': 'lug',
  'Georgian': 'geo',
  'German': 'ger',
  'Greek, Modern (1453-)': 'gre',
  'Guarani': 'grn',
  'Gujarati': 'guj',
  'Haitian; Haitian Creole': 'hat',
  'Hausa': 'hau',
  'Hebrew': 'heb',
  'Herero': 'her',
  'Hindi': 'hin',
  'Hiri Motu': 'hmo',
  'Hungarian': 'hun',
  'Icelandic': 'ice',
  'Ido': 'ido',
  'Igbo': 'ibo',
  'Indonesian': 'ind',
  'Interlingua (International Auxiliary Language Association)': 'ina',
  'Interlingue; Occidental': 'ile',
  'Inuktitut': 'iku',
  'Inupiaq': 'ipk',
  'Irish': 'gle',
  'Italian': 'ita',
  'Japanese': 'jpn',
  'Javanese': 'jav',
  'Kalaallisut; Greenlandic': 'kal',
  'Kannada': 'kan',
  'Kanuri': 'kau',
  'Kashmiri': 'kas',
  'Kazakh': 'kaz',
  'Kikuyu; Gikuyu': 'kik',
  'Kinyarwanda': 'kin',
  'Kirghiz; Kyrgyz': 'kir',
  'Komi': 'kom',
  'Kongo': 'kon',
  'Korean': 'kor',
  'Kuanyama; Kwanyama': 'kua',
  'Kurdish': 'kur',
  'Lao': 'lao',
  'Latin': 'lat',
  'Latvian': 'lav',
  'Limburgan; Limburger; Limburgish': 'lim',
  'Lingala': 'lin',
  'Lithuanian': 'lit',
  'Luba-Katanga': 'lub',
  'Luxembourgish; Letzeburgesch': 'ltz',
  'Macedonian': 'mac',
  'Malagasy': 'mlg',
  'Malay': 'may',
  'Malayalam': 'mal',
  'Maltese': 'mlt',
  'Manx': 'glv',
  'Maori': 'mao',
  'Marathi': 'mar',
  'Marshallese': 'mah',
  'Mongolian': 'mon',
  'Nauru': 'nau',
  'Navajo; Navaho': 'nav',
  'Ndebele, North; North Ndebele': 'nde',
  'Ndebele, South; South Ndebele': 'nbl',
  'Ndonga': 'ndo',
  'Nepali': 'nep',
  'Northern Sami': 'sme',
  'Norwegian': 'nor',
  'Norwegian Nynorsk; Nynorsk, Norwegian': 'nno',
  'Occitan (post 1500)': 'oci',
  'Ojibwa': 'oji',
  'Oriya': 'ori',
  'Oromo': 'orm',
  'Ossetian; Ossetic': 'oss',
  'Pali': 'pli',
  'Panjabi; Punjabi': 'pan',
  'Persian': 'per',
  'Polish': 'pol',
  'Portuguese': 'por',
  'Pushto; Pashto': 'pus',
  'Quechua': 'que',
  'Romanian; Moldavian; Moldovan': 'rum',
  'Romansh': 'roh',
  'Rundi': 'run',
  'Russian': 'rus',
  'Samoan': 'smo',
  'Sango': 'sag',
  'Sanskrit': 'san',
  'Sardinian': 'srd',
  'Serbian': 'srp',
  'Shona': 'sna',
  'Sichuan Yi; Nuosu': 'iii',
  'Sindhi': 'snd',
  'Sinhala; Sinhalese': 'sin',
  'Slovak': 'slo',
  'Slovenian': 'slv',
  'Somali': 'som',
  'Sotho, Southern': 'sot',
  'Spanish; Castilian': 'spa',
  'Sundanese': 'sun',
  'Swahili': 'swa',
  'Swati': 'ssw',
  'Swedish': 'swe',
  'Tagalog': 'tgl',
  'Tahitian': 'tah',
  'Tajik': 'tgk',
  'Tamil': 'tam',
  'Tatar': 'tat',
  'Telugu': 'tel',
  'Thai': 'tha',
  'Tibetan': 'tib',
  'Tigrinya': 'tir',
  'Tonga (Tonga Islands)': 'ton',
  'Tsonga': 'tso',
  'Tswana': 'tsn',
  'Turkish': 'tur',
  'Turkmen': 'tuk',
  'Twi': 'twi',
  'Uighur; Uyghur': 'uig',
  'Ukrainian': 'ukr',
  'Urdu': 'urd',
  'Uzbek': 'uzb',
  'Venda': 'ven',
  'Vietnamese': 'vie',
  'Volapük': 'vol',
  'Walloon': 'wln',
  'Welsh': 'wel',
  'Western Frisian': 'fry',
  'Wolof': 'wol',
  'Xhosa': 'xho',
  'Yiddish': 'yid',
  'Yoruba': 'yor',
  'Zhuang; Chuang': 'zha',
  'Zulu': 'zul'
}
