#!/bin/sh
DVD=/dev/dvd
if [ -n "$1" ] ; then
    DVD="$1"
fi

if [ ! -e "$DVD" ] ; then
    echo "$DVD" not found
    exit 1
fi

if [ ! -f "${DVD}" -a ! -d "${DVD}" ] ; then
    BLKID=$(blkid "$DVD")
    if [ -z "$BLKID" ] ; then 
	echo Waiting for online
    fi
    while [ -z "$BLKID" ] ; do
	BLKID=$(blkid "$DVD")
    done
fi

lsdvd "$DVD" | grep Title | grep -v 0:00: | sed -e 's/ 00:/    /g'
