#!/usr/bin/env python
#
# Copyright 2016 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

import tvdb_api
import sys
from operator import itemgetter
import argparse
import glob
import os
import re
import sys
import math
import csv

reload(sys)
sys.setdefaultencoding('utf-8')

EPID = 0
DVDSEASON = 1
DVDEPISODE = 2
TITLE = 3
ORIGDATE = 4

# FIXME - add option to keep dvd order when renaming
parser = argparse.ArgumentParser()
parser.add_argument("series", help="Name of series on thetvdb.com")
parser.add_argument("--rename", action="store_true", help="rename files to match dvd order")
parser.add_argument("--dvdmissing", action="store_true", help="use episode data when dvd info is missing")
parser.add_argument("--dvdignore", action="store_true", help="ignore dvd episode data")
parser.add_argument("--enumerate", action="store_true", help="Episodes are in order but may have gaps")
parser.add_argument("--first", default=1, help="Start enumeration at this number")
parser.add_argument("--minsize", help="Ignore videos smaller than this")
parser.add_argument("--dvdorder", action="store_true", help="keep episodes in DVD order")
parser.add_argument("--airedorder", action="store_true", help="episodes are currently in aired order")
parser.add_argument("--csv", action="store_true", help="output data as csv")
parser.add_argument("--quiet", action="store_true", help="don't print errors about missing DVD info")
parser.add_argument("--glob", help="pattern for finding videos", default="[0-9]x[0-9][0-9].mkv")
parser.add_argument("--dryrun", action="store_true", help="Don't actually rename files")
args = parser.parse_args()

t = tvdb_api.Tvdb()
show = t[args.series]

series = []

def formatEpisodeID(season, epnum):
  num = 0
  for row in dvdorder:
    if row[DVDSEASON] == season:
      num += 1
  digits = int(math.floor(math.log(num, 10)) + 1)
  if digits < 2:
    digits = 2
  epid = "%%ix%%0%ii" % digits
  return epid % (season, epnum)

def findVideo(episode):
  guess = "\\b" + formatEpisodeID(episode[DVDSEASON], int(episode[DVDEPISODE])) + "\\b"
  indices = [i for i, x in enumerate(videos) if re.search(guess, x)]
  if not len(indices):
    guess = "\\b[sS]%02i[eE]%02i\\b" % (episode[DVDSEASON], int(episode[DVDEPISODE]))
    indices = [i for i, x in enumerate(videos) if re.search(guess, x)]
  if len(indices):
    return videos[indices[0]]
  return None  
  
def findEpisode(epid):
  if type(epid) is int:
    return dvdorder[epid]
  
  for row in dvdorder:
    if epid == row[EPID]:
      return row
  return None

# FIXME - make finding the file as smart as tvrenamer.pl
def renameVid(episode, filename=None):
  epid = episode[EPID]
  if args.dvdorder:
    epid = formatEpisodeID(episode[DVDSEASON], int(episode[DVDEPISODE]))
  if not filename:
    filename = findVideo(episode)

  if filename:
    video, ext = os.path.splitext(filename)
    title = re.sub("[:/]", "-", re.sub("[.!?]+$", "", episode[TITLE]))
    if args.dvdorder:
      part = int((episode[DVDEPISODE] * 10) % 10)
      if part and title.endswith(" (" + str(part) + ")"):
        title = title[:-4]
    eptitle = "%s %s%s" % (epid, title, ext)
    if filename != eptitle:
      if os.path.isfile(eptitle):
        print "Already exists! " + eptitle
      else:
        if not args.dryrun:
          os.rename(filename, eptitle)
        print filename + " to " + eptitle
  return filename

def isint(s):
  try:
    int(s)
    return True
  except ValueError:
    return False
          
for season in show:
  for epnum in show[season]:
    episode = show[season][epnum]
    epid = episode['seasonnumber'] + "x" + episode['episodenumber'].zfill(2)
    epinfo = None
    if args.airedorder:
      epinfo = [epid, int(episode['seasonnumber']), float(episode['episodenumber'])]
    elif not args.dvdignore and episode['dvd_season'] and episode['dvd_episodenumber']:
      epinfo = [epid, int(episode['dvd_season']), float(episode['dvd_episodenumber'])]
    elif not args.dvdignore and episode['dvd_episodenumber']:
      epinfo = [epid, int(episode['seasonnumber']), float(episode['dvd_episodenumber'])]
    else:
      if args.dvdmissing or args.dvdignore:
        epinfo = [epid, int(episode['seasonnumber']), float(episode['episodenumber'])]
      elif not args.quiet:
        print "No DVD info for"
        print episode
    if epinfo:
      epinfo.extend([episode['episodename'], episode['firstaired'],
                    episode['productioncode']])
      series.append(epinfo)
dvdorder = sorted(series, key=itemgetter(1, 2))

videos = [file for file in glob.glob(args.glob)]
videos.sort()

minsize = 0
if args.minsize:
  val = re.sub("^( *[0-9]+).*", "\\1", args.minsize)
  minsize = int(val)
  suffix = args.minsize[-1]
  try:
    magnitude = ["B", "K", "M", "G"].index(suffix.upper())
  except ValueError:
    magnitude = -1
  if magnitude >= 0:
    minsize *= math.pow(1024, magnitude)

if args.csv:
  csvdata = []
  for row in dvdorder:
    info = [row[EPID], "%ix%04.1f" % (row[DVDSEASON], row[DVDEPISODE]), row[ORIGDATE], row[TITLE]]
    csvdata.append(info)

  a = csv.writer(sys.stdout)
  a.writerows(csvdata)
else:
  epnum = 0

  if isint(args.first):
    first = int(args.first)
  else:
    episode = findEpisode(args.first)
    first = dvdorder.index(episode) + 1
    
  for filename in videos:
    if minsize:
      size = os.path.getsize(filename)
      if size < minsize:
        continue
      
    video, ext = os.path.splitext(filename)
    epid = video
    if args.enumerate:
      epid = epnum + first - 1
    episode = findEpisode(epid)
    if args.rename:
      filename = renameVid(episode, filename=filename)
    else:
      print dvdorder.index(episode) + 1,
      for info in episode:
        print episode,
      print
    epnum += 1
