#!/bin/sh
#
# Copyright 2016 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

DUR=0.2		# Set the minimum detected black duration (in seconds)
THRESHOLD=50	# How quiet is silent

while [ $# -gt 0 -a `expr substr "${1:-empty}" 1 2` = "--" ] ; do
    case "$1" in
	--duration)
	    DUR="$2"
	    shift 2
	    ;;
	--threshold)
	    THRESHOLD="$2"
	    shift 2
	    ;;
	*)
	    echo Unknown flag "$1"
	    exit 1
	    ;;
    esac
done

LOGFILE=/tmp/split.$$

VIDEO="$1"
SPLITS="$2"

ffmpeg -i "${VIDEO}" -af silencedetect=n=-${THRESHOLD}dB:d=${DUR} -f null - 2>&1 | tee ${LOGFILE}

tr '\015' '\012' < ${LOGFILE} | egrep 'silence_start:|silence_end:' \
    | awk '/silence_start:/ {ss = $5} /silence_end:/ {n = ss + ($5 - ss) / 2; printf "%.3f %.3f %.3f\n", n, ss, $5}' \
    > "${SPLITS}"

rm -f ${LOGFILE}
