#!/bin/sh
#
# Copyright 2016 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

VIDEO="$1"
SPLITS="$2"

ffprobe -select_streams v -show_frames -show_entries frame=key_frame,pict_type,pkt_pts_time -of csv "${VIDEO}" | grep frame,1, | awk -F, '{print $3}' > "${SPLITS}"
