#!/bin/sh
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

while [ $# -gt 0 -a `expr substr "${1:-empty}" 1 2` = "--" ] ; do
    case "$1" in
	--decomb)
	    FLAGS="${FLAGS} -vf yadif=0:-1:0"
	    shift
	    ;;
	--start)
	    FLAGS="${FLAGS} -ss $2"
	    shift 2
	    ;;
	--stop)
	    FLAGS="${FLAGS} -to $2"
	    shift 2
	    ;;
	*)
	    echo unknown flag "$1"
	    exit 1
	    ;;
    esac
done

SOURCE="$1"
DEST="$2"

if [ -z "${DEST}" ] ; then
    DEST="${SOURCE%.*}"
    while [ -e "${DEST}${COUNTER}.mpg" ] ; do
	if [ -z "${COUNTER}" ] ; then
	    COUNTER=1
	fi
	COUNTER=`expr ${COUNTER} + 1`
    done
    DEST="${DEST}${COUNTER}.mpg"
fi

ffmpeg -threads 4 -i "${SOURCE}" ${FLAGS} -codec:v mpeg2video -qscale:v 8 -codec:a mp2 -b:a 192k "${DEST}"
