#!/bin/sh
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

EXT=mkv

while [ $# -gt 0 -a `expr substr "${1:-empty}" 1 2` = "--" ] ; do
    case "$1" in
	--dvd)
	    DVD="$2"
	    shift 2
	    ;;
	--season)
	    SEASON="$2"
	    shift 2
	    ;;
	--title)
	    TITLE="$2 --chapters"
	    shift 2
	    ;;
	--chapters)
	    FLAGS="${FLAGS} --chapters $2"
	    shift 2
	    ;;
	--split-chapters)
	    SPLIT=1
	    shift
	    ;;
	--crop)
	    FLAGS="${FLAGS} --crop $2"
	    shift 2
	    ;;
	--rate)
	    FLAGS="${FLAGS} --rate $2"
	    shift 2
	    ;;
	--extension)
	    FLAGS="${FLAGS} --extension $2"
	    EXT="$2"
	    shift 2
	    ;;
	--firstep)
	    EPISODE="$2"
	    shift 2
	    ;;
	--animation|--film|--pal-film|--decomb|--pal-animation|--lap-animation|--mangled-pal|--subtitles|--detelecine|--tv|--tv-bob|--restore-ntsc|--cfr)
	    FLAGS="${FLAGS} $1"
	    shift
	    ;;
	--lang)
	    FLAGS="${FLAGS} $1 $2"
	    shift 2
	    ;;
	*)
	    echo "Unknown flag:" "$1"
	    exit 1
	    ;;
    esac
done

if [ -z "${SEASON}" ] ; then
    SEASON=$1
    shift
fi
if [ -z "${EPISODE}" ] ; then
    EPISODE=$1
    shift
fi

TITLES="$@"

if [ -n "${SPLIT}" -a -z "${TITLES}" ] ; then
    echo Chapter splitting requested without specifying titles
    exit 1
fi

# If no titles specified, rip all of them
if [ -z "${TITLES}" ] ; then
    if [ -n "${DVD}" ] ; then
	TITLES=`(lsdvd "${DVD}" 2>/dev/null) | egrep '^Title:' | awk '{printf "%i\n", $2}' | sed -e 's/,//'`
    else
	TITLES=`(lsdvd 2>/dev/null) | egrep '^Title:' | awk '{printf "%i\n", $2}' | sed -e 's/,//'`
    fi
fi

if [ -n "${SPLIT}" ] ; then
    for i in ${TITLES} ; do
	if [ -n "${DVD}" ] ; then
	    CHAPTERS=`(lsdvd -t $i -c "${DVD}" 2>/dev/null) | grep Chapter: | awk '{printf "'$i':%i\n", $2}'`
	else
	    CHAPTERS=`(lsdvd -t $i -c 2>/dev/null) | grep Chapter: | awk '{printf "'$i':%i\n", $2}'`
	fi
	titles="${titles} ${CHAPTERS}"
    done
    TITLES=${titles}
fi

for i in ${TITLES} ; do
    ep=`echo $EPISODE | awk '{printf "%02i\n", $1}'`
    EPISODE=`expr $EPISODE + 1`
    if expr match $i "[0-9][0-9]*:[0-9][0-9]*" > /dev/null ; then
	i=`echo $i | sed -e 's/:/ --chapters /'`
    fi
    if [ -n "${DVD}" ] ; then
	rip-video ${FLAGS} --title ${TITLE} $i "${DVD}" ${SEASON}x${ep}.${EXT}
    else
	rip-video ${FLAGS} --title ${TITLE} $i ${SEASON}x${ep}.${EXT}
    fi
    tput cuu1
    tput el
    size=`ls -lh ${SEASON}x${ep}.${EXT} | awk '{print $5}'`
    echo ${SEASON}x${ep}.${EXT}: $i $size
done

if [ -z "${DVD}" ] ; then
    DVD=/dev/dvd
fi
DVD=$(readlink -f "${DVD}")
DIR=$(echo "${DVD}" | cut -d "/" -f2)
if [ "${DIR}" = dev ] ; then
    eject ${DVD}
fi
