#!/bin/sh
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

FLAGS="--loose-anamorphic"

while [ $# -gt 0 -a `expr substr "${1:-empty}" 1 2` = "--" ] ; do
    case "$1" in
	--gain) 
	    FLAGS="${FLAGS} $1 $2"
	    shift 2
	    ;;
	--dvd)
	    DVD="$2"
	    shift 2
	    ;;
	--title)
	    TITLE="$2"
	    shift 2
	    ;;
	--chapters)
	    CHAPTERS="$2"
	    shift 2
	    ;;
	--animation)
	    FLAGS="${FLAGS} -r 23.976 --vfr --x264-tune animation --decomb --detelecine"
	    shift
	    ;;
	--pal-animation)
	    FLAGS="${FLAGS} --vfr --x264-tune animation --decomb"
	    shift
	    ;;
	--film)
	    FLAGS="${FLAGS} -m -r 23.976 --vfr --x264-tune film --decomb --detelecine"
	    shift
	    ;;
	--decomb)
	    FLAGS="${FLAGS} --decomb"
	    shift
	    ;;
	--subtitles)
	    FLAGS="${FLAGS} --subtitle scan --subtitle-forced"
	    shift
	    ;;
	*)
	    unknown flag "$1"
	    exit 1
	    ;;
    esac
done

if [ -n "${TITLE}" ] ; then
    FLAGS="${FLAGS} --title ${TITLE}"
    SOURCE="${DVD:-/dev/dvd}"
    DEST="$1"
else
    SOURCE="$1"
    DEST="$2"
fi

if [ -n "${CHAPTERS}" ] ; then
    FLAGS="${FLAGS} --chapters ${CHAPTERS}"
fi

if [ -z "${DEST}" ] ; then
    DEST="${SOURCE%.*}"
    while [ -e "${DEST}${COUNTER}.mkv" ] ; do
	if [ -z "${COUNTER}" ] ; then
	    COUNTER=1
	fi
	COUNTER=`expr ${COUNTER} + 1`
    done
    DEST=${DEST}${COUNTER}.mkv
fi

HandBrakeCLI --encoder x264 ${FLAGS} -i "${SOURCE}" -o "${DEST}" 2>/dev/null
