#!/bin/sh
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

while [ $# -gt 0 -a `expr substr "${1:-empty}" 1 2` = "--" ] ; do
    case "$1" in
	--dvd)
	    DVDFLAG="--dvd"
	    DVD="$2"
	    shift 2
	    ;;
	--season)
	    SEASON="$2"
	    shift 2
	    ;;
	--firstep)
	    EPISODE="$2"
	    shift 2
	    ;;
	--animation)
	    FLAGS="${FLAGS} --animation"
	    shift
	    ;;
	--decomb)
	    FLAGS="${FLAGS} --decomb"
	    shift
	    ;;
	--pal-animation)
	    FLAGS="${FLAGS} --pal-animation"
	    shift
	    ;;
	*)
	    echo "Unknown flag:" "$1"
	    exit 1
	    ;;
    esac
done

if [ -z "${SEASON}" ] ; then
    SEASON=$1
    shift
fi
if [ -z "${EPISODE}" ] ; then
    EPISODE=$1
    shift
fi

for i in $@ ; do
    ep=`echo $EPISODE |awk '{printf "%02i\n", $1}'`
    EPISODE=`expr $EPISODE + 1`
    rip-video ${DVDFLAG} "${DVD}" ${FLAGS} --title $i ${SEASON}x${ep}.mkv
done

if [ -z "${DVD}" ] ; then
    eject
fi
