#!/usr/bin/env python3
import argparse
import os, glob

FLAGS="--lang=eng --bluray"

def build_argparser():
  parser = argparse.ArgumentParser()
  parser.add_argument("dirs", nargs="+", help="input files")
  parser.add_argument("--flags", help="flags to pass to rip-video, default is <" + FLAGS + ">")
  # parser.add_argument("--chapters", action="store_true",
  #                     help="add chapter markers at splice points")
  return parser

def main():
  args = build_argparser().parse_args()
  for dir in args.dirs:
    basedir = os.path.basename(dir)
    for file in sorted(glob.glob(os.path.join(dir, "*.mkv"))):
      output = video = os.path.basename(file)
      if not video.startswith(basedir):
        output = basedir + "_" + video
      print(output)
      log, _ = os.path.splitext(output)
      log += ".log"
      # FIXME - if log exists and video exists check length
      if not os.path.exists(log):
        cmd = "rip-video " + FLAGS + " \"%s\" \"%s\"" % (file, output)
        print(cmd)
        os.system(cmd)
  return

if __name__ == '__main__':
  exit(main() or 0)
