#!/usr/bin/awk -f
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

BEGIN {
    p = 0;
    c = 1
}

!/ *#/ {
    n = $4;

    ph = int(p / 3600);
    pm = int((p - ph * 3600) / 60);
    ps = p - ph * 3600 - pm * 60;

    nh = int(n / 3600);
    nm = int((n - nh * 3600) / 60);
    ns = n - nh * 3600 - nm * 60;

    printf "%02i. %02i:%02i:%02i - %02i:%02i:%02i\n", c,
	ph, pm, int(ps+0.5),
	nh, nm, int(ns+0.5);

    p = n;
    c++
}
