#!/usr/bin/env python3
# -*- python -*-
#
# Copyright 2019 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

import argparse
import os
import json
import xmltodict
import re
import tempfile
import shutil
import pty
import subprocess
import sys
from viddin import viddin

def build_argparser():
  parser = argparse.ArgumentParser()
  parser.add_argument("files", nargs="+", help="input files")
  parser.add_argument("dest", help="output file")
  parser.add_argument("--chapters", action="store_true",
                      help="add chapter markers at splice points")
  parser.add_argument("--debug", action="store_true", help="print debug info")
  parser.add_argument("--ffmpeg", action="store_true", help="use ffmpeg to concatenate")
  return parser

def main():
  args = build_argparser().parse_args()
  longest = None
  chapters = []
  for vid in args.files:
    length = viddin.getLength(vid)
    if not longest or length > longest[1]:
      longest = (vid, length)
    if len(chapters):
      length += chapters[-1]
    chapters.append(length)

  dsize = viddin.getResolution(longest[0])
  print(dsize)

  tmpdir = tempfile.mkdtemp()
  print(tmpdir)
  
  inputs = []
  for vid in args.files:
    res = viddin.getResolution(vid)
    if res == dsize:
      inputs.append(os.path.abspath(vid))
    else:
      tmp, ext = os.path.splitext(vid)
      tmp += "_%i" % (args.files.index(vid)) + ext
      tmp = os.path.join(tmpdir, tmp)
      cmd = ["ffmpeg", "-i", vid,
             "-vf", "scale=%i:%i" % (dsize[0], dsize[1]),
             "-c", "copy", "-vcodec", "libx264", "-map", "0", tmp];
      print(cmd)
      viddin.runCommand(cmd, args.debug)
      inputs.append(tmp)

  if args.ffmpeg:
    mergetxt = os.path.join(tmpdir, "merge.txt")
    f = open(mergetxt, "w")
    for vid in inputs:
      f.write("file '%s'\n" % (vid))
    f.close()
    cmd = ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", mergetxt,
           "-c", "copy", args.dest]
  else:
    cmd = ["mkvmerge", "-o", args.dest]
    for vid in inputs:
      idx = inputs.index(vid)
      if idx:
        cmd.append("+")
      cmd.append(vid)

  print(cmd)
  viddin.runCommand(cmd, args.debug)

  shutil.rmtree(tmpdir)

  if args.chapters:
    chapters.sort()
    if len(chapters) > 0 and chapters[0] < 2:
      chapters[0] = 0
    else:
      chapters.insert(0, 0)
    vfile = viddin.VideoSpec(args.dest)
    vfile.writeChapters(chapters)
    
  return

if __name__ == '__main__':
  exit(main() or 0)
