#!/usr/bin/env python3
# -*- python -*-
#
# Copyright 2018 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

# FIXME - make this a symlink to trackinfo and make it filter the subs

import os
import sys
import argparse
import json
import xmltodict

sys.path.append(os.path.dirname(os.path.realpath(__file__)))
from viddin import viddin

def build_argparser():
  parser = argparse.ArgumentParser()
  parser.add_argument("source", nargs="?", help="input file")
  parser.add_argument("--title", help="title number to rip")
  parser.add_argument("--lang", help="only use subtitles in specified language")
  return parser

def main():
  args = build_argparser().parse_args()
  title = None
  if args.title:
    title = int(args.title)
    if args.source:
      source = args.source
    else:
      source = "/dev/dvd"
  else:
    source = args.source

  if not os.path.exists(source):
    print("%s does not exist" % (source))
    sys.exit(1)

  subs = getSubs(source, title)
  for sub in subs:
    info = "%i:" % (sub['rv_track_id'])

    info += " Forced="
    if 'forced_track' in sub and sub['forced_track']:
      info += "Yes"
    else:
      info += "No"

    if 'uid' in sub:
      info += " UID=%i" % (sub['uid'])

    if 'language' in sub:
      lang = sub['language']
      if args.lang and lang != args.lang:
        continue
      info += " Language=%s" % (lang)

    if 'DURATION' in sub:
      info += " Duration=%s" % (sub['DURATION'])

    if 'NUMBER_OF_FRAMES' in sub:
      info += " Frames=%s" % (sub['NUMBER_OF_FRAMES'])

    if 'NUMBER_OF_BYTES' in sub:
      info += " Bytes=%s" % (sub['NUMBER_OF_BYTES'])

    if 'codec_id' in sub:
      info += " Codec=%s" % (sub['codec_id'])

    print(info)
  return

if __name__ == '__main__':
  exit(main() or 0)
