#!/usr/bin/env python3
# -*- python -*-
#
# Copyright 2018 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

import os
import sys
import argparse
import json
import xmltodict

sys.path.append(os.path.dirname(os.path.realpath(__file__)))
from viddin import viddin

def build_argparser():
  parser = argparse.ArgumentParser()
  parser.add_argument("source", help="input file")
  parser.add_argument("--title", help="title number to rip")
  parser.add_argument("--lang", help="only use subtitles in specified language")
  return parser

def trackWithUid(uid, tracks):
  for track in tracks:
    if 'uid' in track and uid == track['uid']:
      return track
  return None

def main():
  args = build_argparser().parse_args()
  if not os.path.exists(args.source):
    print("Unable to locate " + args.source)
    sys.exit(1)

  tinfo = viddin.getTitleInfo(args.source, args.title)
  tracks = []
  tracks.extend(tinfo.video)
  tracks.extend(tinfo.audio)
  tracks.extend(tinfo.subtitles)
  for track in tracks:
    if 'DURATION' not in track:
      track['DURATION'] = str(tinfo.length)
      
    info = "%i:" % (track['rv_track_id'])

    info += " Type=" + track['type']

    info += " Forced="
    if 'forced_track' in track and track['forced_track']:
      info += "Yes"
    else:
      info += "No"

    if 'uid' in track:
      info += " UID=%i" % (track['uid'])

    if 'language' in track:
      lang = track['language']
      if args.lang and lang != args.lang:
        continue
      info += " Language=%s" % (lang)

    if 'DURATION' in track:
      dur = viddin.decodeTimecode(track['DURATION'])
      info += " Duration=%s" % (viddin.formatTimecode(dur))

    if 'NUMBER_OF_FRAMES' in track:
      info += " Frames=%s" % (track['NUMBER_OF_FRAMES'])

    if 'NUMBER_OF_BYTES' in track:
      info += " Bytes=%s" % (track['NUMBER_OF_BYTES'])

    if 'codec' in track:
      info += " Codec=%s" % (track['codec'])

    if 'audio_channels' in track:
      info += " Channels=%s" % (track['audio_channels'])

    print(info)
  return

if __name__ == '__main__':
  exit(main() or 0)
