#!/bin/sh
#
# Copyright 2015 by Chris Osborn <fozztexx@fozztexx.com>
#
# This file is part of viddin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

if ! type mplayer > /dev/null ; then
    echo mplayer not installed
    exit 1
fi

PRINTNAME=0
if [ $# -gt 1 ] ; then
    PRINTNAME=1
fi

while [ $# -gt 0 ] ; do
    NAME=""
    if [ $PRINTNAME -gt 0 ] ; then
	NAME="${1}:"
    fi
    mplayer -identify -frames 0 -vc null -vo null -ao null "$1" 2>/dev/null \
	| egrep '^[A-Z90-9_]+=' | sort -u | \
	awk '{printf "'"${NAME}"'%s\n", $0}'
    shift
done
